export type { UserProfile, Gender, FitnessGoal, ActivityLevel, WeightUnit } from './user'
export { GOAL_LABELS, ACTIVITY_LABELS } from './user'
export type { WeightEntry } from './weight'
export type { FoodItem, MealEntry, MealType, WaterEntry, DailyNutrition } from './nutrition'
export { MEAL_LABELS, MEAL_ICONS, scaleMacros, sumNutrition, sumWater } from './nutrition'
