/**
 * EXERCISE_MEDIA — generated by scripts/buildExerciseCatalog.mjs
 * Real exercise animations (H.264 demo videos / animated illustrations) sourced
 * from wger.de and matched to every FitTracker exercise id. Do not edit by hand.
 * License: CC BY-SA 4.0 — https://wger.de
 */

export interface ExerciseMedia {
  /** wger.de exercise id (for credit links) */
  wgerId: number
  /** wger exercise name this was matched to */
  match: string
  /** Browser-playable demo video (preferred visual) */
  video?: string
  /** Illustration (animated webp when animated=true, still otherwise) */
  image?: string
  /** image is an animated webp */
  animated?: boolean
  /** small static thumbnail */
  thumb?: string
}

export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {
  "bench_press": {
    "wgerId": 73,
    "match": "Bench Press",
    "video": "https://wger.de/media/exercise-video/73/cfb72002-898f-443a-a124-a0bce8a2e6ad.MP4",
    "image": "https://wger.de/media/exercise-images/192/Bench-press-1.png",
    "thumb": "https://wger.de/media/exercise-images/192/Bench-press-1.png.400x400_q85.png"
  },
  "incline_bench": {
    "wgerId": 538,
    "match": "Incline Bench Press - Barbell",
    "image": "https://wger.de/media/exercise-images/41/Incline-bench-press-1.png",
    "thumb": "https://wger.de/media/exercise-images/41/Incline-bench-press-1.png.400x400_q85.jpg"
  },
  "db_bench": {
    "wgerId": 73,
    "match": "Bench Press",
    "video": "https://wger.de/media/exercise-video/73/cfb72002-898f-443a-a124-a0bce8a2e6ad.MP4",
    "image": "https://wger.de/media/exercise-images/192/Bench-press-1.png",
    "thumb": "https://wger.de/media/exercise-images/192/Bench-press-1.png.400x400_q85.png"
  },
  "db_fly": {
    "wgerId": 237,
    "match": "Fly With Cable",
    "image": "https://wger.de/media/exercise-images/122/Incline-cable-flyes-1.png",
    "thumb": "https://wger.de/media/exercise-images/122/Incline-cable-flyes-1.png.400x400_q85.jpg"
  },
  "pushup": {
    "wgerId": 1551,
    "match": "Push-Up",
    "image": "https://wger.de/media/exercise-images/1551/a6a9e561-3965-45c6-9f2b-ee671e1a3a45.png",
    "thumb": "https://wger.de/media/exercise-images/1551/a6a9e561-3965-45c6-9f2b-ee671e1a3a45.png.400x400_q85.jpg"
  },
  "cable_fly": {
    "wgerId": 237,
    "match": "Fly With Cable",
    "image": "https://wger.de/media/exercise-images/122/Incline-cable-flyes-1.png",
    "thumb": "https://wger.de/media/exercise-images/122/Incline-cable-flyes-1.png.400x400_q85.jpg"
  },
  "deadlift": {
    "wgerId": 184,
    "match": "Deadlifts",
    "image": "https://wger.de/media/exercise-images/184/1709c405-620a-4d07-9658-fade2b66a2df.jpeg",
    "thumb": "https://wger.de/media/exercise-images/184/1709c405-620a-4d07-9658-fade2b66a2df.jpeg.400x400_q85.jpg"
  },
  "pullup": {
    "wgerId": 475,
    "match": "Pull-ups",
    "image": "https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg",
    "thumb": "https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg.400x400_q85.jpg"
  },
  "chinup": {
    "wgerId": 152,
    "match": "Chin Up",
    "image": "https://wger.de/media/exercise-images/152/6c1a7459-266d-491a-bd50-7cbaea2bc771.png",
    "thumb": "https://wger.de/media/exercise-images/152/6c1a7459-266d-491a-bd50-7cbaea2bc771.png.400x400_q85.png"
  },
  "bent_row": {
    "wgerId": 83,
    "match": "Bent Over Rowing",
    "image": "https://wger.de/media/exercise-images/109/Barbell-rear-delt-row-1.png",
    "thumb": "https://wger.de/media/exercise-images/109/Barbell-rear-delt-row-1.png.400x400_q85.jpg"
  },
  "db_row": {
    "wgerId": 1637,
    "match": "Single arm row",
    "image": "https://wger.de/media/exercise-images/1637/a1fbe83a-a3e5-49f6-a2c2-5d5b533c2be8.png",
    "thumb": "https://wger.de/media/exercise-images/1637/a1fbe83a-a3e5-49f6-a2c2-5d5b533c2be8.png.400x400_q85.png"
  },
  "lat_pulldown": {
    "wgerId": 1127,
    "match": "Close-grip supinated lat pulldown",
    "image": "https://wger.de/media/exercise-images/1127/4942b7c0-6bda-4983-88e5-86547c3d445e.png",
    "thumb": "https://wger.de/media/exercise-images/1127/4942b7c0-6bda-4983-88e5-86547c3d445e.png.400x400_q85.jpg"
  },
  "seated_cable_row": {
    "wgerId": 1117,
    "match": "Seated Cable Row",
    "image": "https://wger.de/media/exercise-images/1117/2555c4c3-a84d-47db-b83b-cbf721f12e45.png",
    "thumb": "https://wger.de/media/exercise-images/1117/2555c4c3-a84d-47db-b83b-cbf721f12e45.png.400x400_q85.jpg"
  },
  "ohp": {
    "wgerId": 1893,
    "match": "Overhead Barbell Press",
    "image": "https://wger.de/media/exercise-images/1893/7dbad19e-0616-41fd-9d7d-3e21649c0eea.png",
    "thumb": "https://wger.de/media/exercise-images/1893/7dbad19e-0616-41fd-9d7d-3e21649c0eea.png.400x400_q85.png"
  },
  "db_shoulder_press": {
    "wgerId": 567,
    "match": "Shoulder Press, Dumbbells",
    "image": "https://wger.de/media/exercise-images/123/dumbbell-shoulder-press-large-1.png",
    "thumb": "https://wger.de/media/exercise-images/123/dumbbell-shoulder-press-large-1.png.400x400_q85.jpg"
  },
  "lateral_raise": {
    "wgerId": 348,
    "match": "Lateral Raises",
    "image": "https://wger.de/media/exercise-images/148/lateral-dumbbell-raises-large-2.png",
    "thumb": "https://wger.de/media/exercise-images/148/lateral-dumbbell-raises-large-2.png.400x400_q85.jpg"
  },
  "front_raise": {
    "wgerId": 256,
    "match": "Front Raises",
    "image": "https://wger.de/media/exercise-images/256/b7def5bc-2352-499b-b9e5-fff741003831.png",
    "thumb": "https://wger.de/media/exercise-images/256/b7def5bc-2352-499b-b9e5-fff741003831.png.400x400_q85.jpg"
  },
  "face_pull": {
    "wgerId": 1639,
    "match": "Dumbbell Bent Over Face Pull",
    "image": "https://wger.de/media/exercise-images/1639/8927346e-f5ca-4795-bdf1-5ac9309401e7.webp",
    "thumb": "https://wger.de/media/exercise-images/1639/8927346e-f5ca-4795-bdf1-5ac9309401e7.webp.400x400_q85.jpg"
  },
  "barbell_curl": {
    "wgerId": 91,
    "match": "Biceps Curls With Barbell",
    "image": "https://wger.de/media/exercise-images/74/Bicep-curls-1.png",
    "thumb": "https://wger.de/media/exercise-images/74/Bicep-curls-1.png.400x400_q85.png"
  },
  "db_curl": {
    "wgerId": 92,
    "match": "Biceps Curls With Dumbbell",
    "image": "https://wger.de/media/exercise-images/81/Biceps-curl-1.png",
    "thumb": "https://wger.de/media/exercise-images/81/Biceps-curl-1.png.400x400_q85.png"
  },
  "hammer_curl": {
    "wgerId": 272,
    "match": "Hammer Curls",
    "image": "https://wger.de/media/exercise-images/86/Bicep-hammer-curl-1.png",
    "thumb": "https://wger.de/media/exercise-images/86/Bicep-hammer-curl-1.png.400x400_q85.png"
  },
  "preacher_curl": {
    "wgerId": 465,
    "match": "Preacher Curls",
    "image": "https://wger.de/media/exercise-images/193/Preacher-curl-3-1.png",
    "thumb": "https://wger.de/media/exercise-images/193/Preacher-curl-3-1.png.400x400_q85.png"
  },
  "close_grip_bench": {
    "wgerId": 76,
    "match": "Bench Press Narrow Grip",
    "image": "https://wger.de/media/exercise-images/88/Narrow-grip-bench-press-1.png",
    "thumb": "https://wger.de/media/exercise-images/88/Narrow-grip-bench-press-1.png.400x400_q85.png"
  },
  "tricep_pushdown": {
    "wgerId": 805,
    "match": "Tricep Pushdown on Cable",
    "image": "https://wger.de/media/exercise-images/805/7a437824-e2cc-46e1-804a-674f0ea31d25.png",
    "thumb": "https://wger.de/media/exercise-images/805/7a437824-e2cc-46e1-804a-674f0ea31d25.png.400x400_q85.png"
  },
  "skull_crusher": {
    "wgerId": 246,
    "match": "Skullcrusher SZ-bar",
    "video": "https://wger.de/media/exercise-video/246/75eb8c88-922e-45c5-8be3-ac073f62b63f.MP4",
    "image": "https://wger.de/media/exercise-images/84/Lying-close-grip-triceps-press-to-chin-1.png",
    "thumb": "https://wger.de/media/exercise-images/84/Lying-close-grip-triceps-press-to-chin-1.png.400x400_q85.png"
  },
  "dips": {
    "wgerId": 194,
    "match": "Dips",
    "video": "https://wger.de/media/exercise-video/194/d039ec90-474d-47a9-a3ad-bf0b00828c82.MP4",
    "image": "https://wger.de/media/exercise-images/194/34600351-8b0b-4cb0-8daa-583537be15b0.png",
    "thumb": "https://wger.de/media/exercise-images/194/34600351-8b0b-4cb0-8daa-583537be15b0.png.400x400_q85.png"
  },
  "plank": {
    "wgerId": 458,
    "match": "Plank",
    "image": "https://wger.de/media/exercise-images/458/b7bd9c28-9f1d-4647-bd17-ab6a3adf5770.png",
    "thumb": "https://wger.de/media/exercise-images/458/b7bd9c28-9f1d-4647-bd17-ab6a3adf5770.png.400x400_q85.png"
  },
  "crunch": {
    "wgerId": 167,
    "match": "Crunches",
    "image": "https://wger.de/media/exercise-images/91/Crunches-1.png",
    "thumb": "https://wger.de/media/exercise-images/91/Crunches-1.png.400x400_q85.png"
  },
  "leg_raise": {
    "wgerId": 377,
    "match": "Leg Raises, Lying",
    "image": "https://wger.de/media/exercise-images/125/Leg-raises-2.png",
    "thumb": "https://wger.de/media/exercise-images/125/Leg-raises-2.png.400x400_q85.png"
  },
  "ab_wheel": {
    "wgerId": 41,
    "match": "Barbell Ab Rollout",
    "image": "https://wger.de/media/exercise-images/41/34b37423-269f-43d4-9d29-d2a90eeaa6b4.png",
    "thumb": "https://wger.de/media/exercise-images/41/34b37423-269f-43d4-9d29-d2a90eeaa6b4.png.400x400_q85.png"
  },
  "squat": {
    "wgerId": 1801,
    "match": "Barbell Full Squat",
    "image": "https://wger.de/media/exercise-images/1801/60043328-1cfb-4289-9865-aaf64d5aaa28.jpg",
    "thumb": "https://wger.de/media/exercise-images/1801/60043328-1cfb-4289-9865-aaf64d5aaa28.jpg.400x400_q85.jpg"
  },
  "front_squat": {
    "wgerId": 1640,
    "match": "Dumbbell Front Squat",
    "image": "https://wger.de/media/exercise-images/1640/bdea82f1-15ef-4649-8b5a-1303cfc178e7.webp",
    "thumb": "https://wger.de/media/exercise-images/1640/bdea82f1-15ef-4649-8b5a-1303cfc178e7.webp.400x400_q85.jpg"
  },
  "leg_press": {
    "wgerId": 371,
    "match": "Leg Press",
    "image": "https://wger.de/media/exercise-images/371/d2136f96-3a43-4d4c-9944-1919c4ca1ce1.webp",
    "animated": true,
    "thumb": "https://wger.de/media/exercise-images/371/d2136f96-3a43-4d4c-9944-1919c4ca1ce1.webp.400x400_q85.png"
  },
  "lunge": {
    "wgerId": 984,
    "match": "Lunges",
    "image": "https://wger.de/media/exercise-images/984/5c7ffe68-e7b2-47f3-a22a-f9cc28640432.png",
    "thumb": "https://wger.de/media/exercise-images/984/5c7ffe68-e7b2-47f3-a22a-f9cc28640432.png.400x400_q85.jpg"
  },
  "leg_extension": {
    "wgerId": 369,
    "match": "Leg Extension",
    "image": "https://wger.de/media/exercise-images/369/78c915d1-e46d-4d30-8124-65d68664c3ef.png",
    "thumb": "https://wger.de/media/exercise-images/369/78c915d1-e46d-4d30-8124-65d68664c3ef.png.400x400_q85.jpg"
  },
  "rdl": {
    "wgerId": 507,
    "match": "Romanian Deadlift",
    "image": "https://wger.de/media/exercise-images/507/13d526ab-12fc-461e-828a-051dd7c13fb1.png",
    "thumb": "https://wger.de/media/exercise-images/507/13d526ab-12fc-461e-828a-051dd7c13fb1.png.400x400_q85.png"
  },
  "leg_curl": {
    "wgerId": 365,
    "match": "Leg Curls (laying)",
    "image": "https://wger.de/media/exercise-images/154/lying-leg-curl-machine-large-1.png",
    "thumb": "https://wger.de/media/exercise-images/154/lying-leg-curl-machine-large-1.png.400x400_q85.jpg"
  },
  "hip_thrust": {
    "wgerId": 294,
    "match": "Hip Thrust"
  },
  "glute_bridge": {
    "wgerId": 265,
    "match": "Glute Bridge",
    "image": "https://wger.de/media/exercise-images/265/7528acb4-b2cc-4b75-b6ae-d514cbd4f78b.png",
    "thumb": "https://wger.de/media/exercise-images/265/7528acb4-b2cc-4b75-b6ae-d514cbd4f78b.png.400x400_q85.png"
  },
  "calf_raise": {
    "wgerId": 622,
    "match": "Standing Calf Raises",
    "image": "https://wger.de/media/exercise-images/622/9a429bd0-afd3-4ad0-8043-e9beec901c81.jpeg",
    "thumb": "https://wger.de/media/exercise-images/622/9a429bd0-afd3-4ad0-8043-e9beec901c81.jpeg.400x400_q85.jpg"
  },
  "treadmill_run": {
    "wgerId": 1615,
    "match": "Treadmill Cardio",
    "image": "https://wger.de/media/exercise-images/1615/7792295c-83b6-4ea8-9353-ce02f0ad2559.jpg",
    "thumb": "https://wger.de/media/exercise-images/1615/7792295c-83b6-4ea8-9353-ce02f0ad2559.jpg.400x400_q85.jpg"
  },
  "rowing": {
    "wgerId": 513,
    "match": "Rowing, T-bar",
    "image": "https://wger.de/media/exercise-images/106/T-bar-row-1.png",
    "thumb": "https://wger.de/media/exercise-images/106/T-bar-row-1.png.400x400_q85.png"
  },
  "marching": {
    "wgerId": 1965,
    "match": "Marching High Knees",
    "image": "https://wger.de/media/exercise-images/1965/03c08a42-dedb-4a46-8d15-acaf497a35a2.png",
    "thumb": "https://wger.de/media/exercise-images/1965/03c08a42-dedb-4a46-8d15-acaf497a35a2.png.400x400_q85.png"
  },
  "bird_dog": {
    "wgerId": 1572,
    "match": "Bird Dog",
    "image": "https://wger.de/media/exercise-images/1572/3d14e761-a73d-49da-8804-f3016a7573ff.png",
    "thumb": "https://wger.de/media/exercise-images/1572/3d14e761-a73d-49da-8804-f3016a7573ff.png.400x400_q85.jpg"
  },
  "calf_raise_preg": {
    "wgerId": 622,
    "match": "Standing Calf Raises",
    "image": "https://wger.de/media/exercise-images/622/9a429bd0-afd3-4ad0-8043-e9beec901c81.jpeg",
    "thumb": "https://wger.de/media/exercise-images/622/9a429bd0-afd3-4ad0-8043-e9beec901c81.jpeg.400x400_q85.jpg"
  }
}
